# AUTO-GENERATED BY ALPHA ENGINE - DO NOT EDIT
# Do not edit manually. These map to the Phase 2 feature matrix.

class Context:
    CLOSE = "close"
    VOLUME = "volume"

    # --- HYPERPARAMETERS ---
    RSI_LOWER = "rsi_lower"
    RSI_UPPER = "rsi_upper"

    # --- FEATURES ---
    RSI_14 = "RSI_14"
