import json
import os
# Import from src.features to ensure FEATURE_REGISTRY is populated via dynamic loading
from src.features import Feature, FEATURE_REGISTRY

class WorkspaceManager:
    """The GUI-to-Code Bridge: Syncs manifest and generates context helper."""
    def __init__(self, strategy_path: str):
        self.path = strategy_path
        self.manifest_path = os.path.join(self.path, "manifest.json")
        self.context_path = os.path.join(self.path, "context.py")
        os.makedirs(self.path, exist_ok=True)
        # Ensure context.py is available for model.py immediately
        self.refresh()

    def sync(self, features: list, hyperparams: dict, parameter_bounds: dict = None):
        """Called by the GUI to update the strategy's local environment."""
        # Save state to manifest
        manifest = {
            "features": features, 
            "hyperparameters": hyperparams,
            "parameter_bounds": parameter_bounds or {}
        }
        with open(self.manifest_path, 'w') as f:
            json.dump(manifest, f, indent=4)

        self.refresh()

    def refresh(self):
        """Reads manifest.json and auto-generates context.py."""
        if not os.path.exists(self.manifest_path):
            return

        with open(self.manifest_path, 'r') as f:
            manifest = json.load(f)
            
        features = manifest.get('features', [])
        hyperparams = manifest.get('hyperparameters', {})
        
        # Generate context helper for IDE autocomplete
        with open(self.context_path, 'w') as f:
            f.write("# AUTO-GENERATED BY ALPHA ENGINE - DO NOT EDIT\n\n")
            
            # 1. Generate Hyperparameter Constants
            if hyperparams:
                f.write("# --- HYPERPARAMETERS ---\n")
                for hp_key in hyperparams.keys():
                    var_name = hp_key.upper().replace("-", "_").replace(".", "_")
                    f.write(f'{var_name} = "{hp_key}"\n')
                f.write("\n")

            # 2. Generate Feature Constants
            if features:
                f.write("# --- FEATURES ---\n")
                for feat in features:
                    if isinstance(feat, dict):
                        feat_id = feat.get('id', '')
                        params = feat.get('params', {})
                        
                        if feat_id in FEATURE_REGISTRY:
                            feature_cls = FEATURE_REGISTRY[feat_id]
                            feature_instance = feature_cls()
                            
                            # Generate keys for ALL outputs of this feature
                            for output_suffix in feature_instance.outputs:
                                val_name = Feature.generate_column_name(feat_id, params, output_suffix)
                                var_name = val_name.upper().replace("-", "_").replace(".", "_")
                                f.write(f'{var_name} = "{val_name}"\n')
                        else:
                            # Fallback for unregistered features
                            val_name = Feature.generate_column_name(feat_id, params)
                            var_name = val_name.upper().replace("-", "_").replace(".", "_")
                            f.write(f'{var_name} = "{val_name}"\n')
                    else:
                        # Legacy string-only features
                        var_name = feat.upper().replace("(", "_").replace(")", "").replace(",", "_").replace(".", "_")
                        val_name = feat
                        f.write(f'{var_name} = "{val_name}"\n')
