import json
import os

class WorkspaceManager:
    """The GUI-to-Code Bridge: Syncs manifest and generates context helper."""
    def __init__(self, strategy_path: str):
        self.path = strategy_path
        self.manifest_path = os.path.join(self.path, "manifest.json")
        self.context_path = os.path.join(self.path, "context.py")
        os.makedirs(self.path, exist_ok=True)

    def sync(self, features: list, hyperparams: dict, parameter_bounds: dict = None):
        """Called by the GUI to update the strategy's local environment."""
        # Save state to manifest
        manifest = {
            "features": features, 
            "hyperparameters": hyperparams,
            "parameter_bounds": parameter_bounds or {}
        }
        with open(self.manifest_path, 'w') as f:
            json.dump(manifest, f, indent=4)

        # Generate context helper for IDE autocomplete
        with open(self.context_path, 'w') as f:
            f.write("# AUTO-GENERATED BY ALPHA ENGINE - DO NOT EDIT\n\n")
            for feat in features:
                if isinstance(feat, dict):
                    feat_id = feat.get('id', '')
                    params = feat.get('params', {})
                    # Simple period-based indicators use ID_PERIOD format
                    if 'period' in params and len(params) == 1:
                        var_name = f"{feat_id}_{params['period']}".upper()
                        val_name = f"{feat_id}_{params['period']}"
                    else:
                        param_str = "_".join([f"{k}{v}" for k, v in sorted(params.items())])
                        var_name = f"{feat_id}_{param_str}".upper()
                        val_name = f"{feat_id}_{param_str}"
                else:
                    var_name = feat.upper().replace("(", "_").replace(")", "").replace(",", "_")
                    val_name = feat

                f.write(f'{var_name} = "{val_name}"\n')
